### ISSUE TITLE
wrong results with random inputs

### ISSUE THREAD

**Issue by gillbam** [Cjkkkk/CUDA_gemm#3]
Hello,

thanks for your great work! When I set the input matrices to random value, like 

`for( int i = 0; i < M * K; i++ ) {
      h_A[i] = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
    }
   
    for( int i = 0; i < K * N; i++ ) {
      h_B[i] = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
}`

I got unpassed verification by using benchmark_dense.cu. Do you have any idea about this?

Best regards

**Comment by Cjkkkk** [comment]
HI @gillbam , thanks for the report. Could you tell me the matrix size you are testing?

**Comment by gillbam** [comment]
M = 30000
N = K = 64
`Error! Matrix[1918976]=0.00000000, ref=13.65435410 error term is > 1.000000E-06`
it seems the first 1918976 elementes are right, rest are skipped? by the way 1918976 = 29984 * 64

**Comment by Cjkkkk** [comment]
I think the dimension should be divisible by the blocking factor(BLOCK_SIZE_M , BLOCK_SIZE_K, BLOCK_SIZE_N). For non divisible dimension, you can add padding or add if-else in benchmark_dense.cu. You can also refer to TVM GEMM GPU implementation which has basically same implementation but deals with non divisible demension.

**Comment by gillbam** [comment]
thanks for the info!
