### ISSUE TITLE
Wrong boundary conditions

### ISSUE THREAD

**Issue by gillbam** [Cjkkkk/CUDA_gemm#4]
I believe you are using the boundary of C for matrices A and B

https://github.com/Cjkkkk/CUDA_gemm/blob/14b517370609d322647c55fe9136b6d81c2ba9a7/src/cuda/dense.cu#L107
https://github.com/Cjkkkk/CUDA_gemm/blob/14b517370609d322647c55fe9136b6d81c2ba9a7/src/cuda/dense.cu#L125

**Comment by Cjkkkk** [comment]
Yes. I think it is a mistake. Thanks for point it out. Will fix this later.

**Comment by Cjkkkk** [comment]
Fixed and Closed.
